#!/bin/bash
  set -e
  
WIFI_DEVICE="1"
WIFI_SSID="2"
WIFI_PASSPHRASE="3"
DISK_DEV_FILE="/dev/nvme0n1"
DISK_PART_EFI_DEV_FILE="/dev/nvme0n1p1"
DISK_PART_SWAP_DEV_FILE="/dev/nvme0n1p2"
DISK_PART_ROOT_DEV_FILE="/dev/nvme0n1p3"
BOOTLOADER_ID="d"
USER_NAME="f"
USER_PASSWORD="g"
